// Generated by scripts/sync-reference-data.mjs. Do not edit by hand.

export interface GeneratedBurnDecision {
  id: string;
  satellite: string;
  debris: string;
  missBefore: string;
  missAfter: string;
  deltaV: string;
  uploadStation: string;
  leadTime: string;
}

export interface GeneratedVerificationStat {
  label: string;
  value: string;
  accent: 'accent' | 'primary' | 'warning';
}

export const readinessLines: readonly string[] = [
  "[demo-readiness]",
  "{",
  "  \"verdict\": \"ready\",",
  "  \"successful_avoids\": 2,",
  "  \"fleet_collisions_avoided\": 2,",
  "  \"executed_burns\": 2,",
  "  \"dropped_burns\": 0,",
  "  \"fuel_consumed_kg\": 0.1869",
  "}",
  "[confirmed-avoids]",
  "SAT-67060 -> DEB-SYNTH-97001",
  "SAT-67061 -> DEB-SYNTH-97101"
];

export const burnDecision: GeneratedBurnDecision = {
  "id": "AUTO-COLA-4-0",
  "satellite": "SAT-67060",
  "debris": "DEB-SYNTH-97001",
  "missBefore": "8.0 m",
  "missAfter": "134.4 m",
  "deltaV": "0.50 m/s",
  "uploadStation": "GS-003",
  "leadTime": "~9.8 min"
};

export const burnDecisionSecondary: GeneratedBurnDecision | null = {
  "id": "AUTO-COLA-4-1",
  "satellite": "SAT-67061",
  "debris": "DEB-SYNTH-97101",
  "missBefore": "8.1 m",
  "missAfter": "100.5 m",
  "deltaV": "0.50 m/s",
  "uploadStation": "GS-003",
  "leadTime": "~7.2 min"
};

export const verificationStats: readonly GeneratedVerificationStat[] = [
  {
    "label": "Successful avoids",
    "value": "2",
    "accent": "accent"
  },
  {
    "label": "Dropped burns",
    "value": "0",
    "accent": "primary"
  },
  {
    "label": "Fuel used",
    "value": "0.1869 kg",
    "accent": "warning"
  }
];
